version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: nexicore_postgres
    environment:
      POSTGRES_USER: nexicore_user
      POSTGRES_PASSWORD: nexicore_password
      POSTGRES_DB: nexicore_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
